spring:
  data:
    mongodb:
      uri: mongodb+srv://behealthy-admin:behealthy123@cluster0.0ifploi.mongodb.net/?retryWrites=true&w=majority
      database: BeHealthy
  mvc:
    format:
      date: yyyy-MM-dd
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.sa-east-1.amazonaws.com/sa-east-1_rWE5UOOsn