run-name: Build and Deploy | BeHealty - User - API
env: 
  FULL_IMAGE_NAME: behealthy-apis:nutrition-api
 
on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      [closed]
    branches:
      - 'main'
jobs:
  Build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
          
      - name: Build by DockerFile
        run:  docker build . --file Dockerfile --tag ${{ env.FULL_IMAGE_NAME }} 
        
      - name: List docker images available
        run: docker images
        
      - name: Push to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_USER_TOKEN }}
      
      - name: Docker Push
        run: docker tag ${{ env.FULL_IMAGE_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ env.FULL_IMAGE_NAME }}
          && docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.FULL_IMAGE_NAME }}
          
  Deploy:
    name: Deploy to EC2 nutrition-api
    runs-on: ubuntu-latest
    needs: Build
    env: 
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PWD:  ${{ secrets.DOCKER_USER_TOKEN }}
      EC2_TAG_NAME: api
      SERVICE_PORT: ${{ secrets.PORT }}
      EC2_FULL_NAME: behealthy-apis:nutrition-api
    steps:
      - name: Pull and Run Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_NUTRITION_API_HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          envs: DOCKER_USER, DOCKER_PWD, EC2_TAG_NAME, SERVICE_PORT, EC2_FULL_NAME
          script: |
            docker login -u $DOCKER_USER -p $DOCKER_PWD
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docker rmi $(docker images -q)
            docker image pull ${{ secrets.DOCKER_USERNAME }}/$EC2_FULL_NAME
            docker run -d --name $EC2_TAG_NAME -p $SERVICE_PORT:$SERVICE_PORT griebelergabriel/$EC2_FULL_NAME
